#!/usr/bin/env bash

file="$1"
type=$(file --dereference --brief --mime-type "$1")
label_type=$(file --brief "$1")

declare -A cernsor_array=( [$HOME/.arcrc]=1  [$HOME/.irssi/config]=1 [$HOME/.config/gh/hosts.yml]=1)

censor(){
    if [[ -n "${cernsor_array[$file]}" ]]
    then
        echo "🛑 Preview censored 🛑"
        exit
    fi

    case "$label_type" in
        "OpenSSH private key") echo "🛑 Preview censored 🛑";;
        *) get_mime;;
    esac
}

get_mime(){
    case "$type" in
        video/*|audio/*|application/octet-steam) mediainfo "$file";;
        # I hope that sixel support will be available in lf
        image/*) mediainfo "$file" && img2sixel -w 512 "$file";;
        text/x-shellscript) highlight --out-format=ansi "$file";;
        text/*|*/xml|application/json) highlight --out-format=ansi --force "$file";;
        application/vnd.oasis.opendocument.text|*opendocument*) odt2txt "$1";;
        application/x-executable|application/x-pie-executable|application/x-dosexec|application/x-sharedlib) file --brief "$file" | sed "s/), /), \n/g;s/, B/,\nB/g" && echo "" && rabin2 -I "$file";;
        *) cat "$file";;
    esac
}

case "$1" in
    *.zip) zipinfo "$1";;
    *.tar) tar -tvf "$1";;
    *.tar.*) tar -tvf "$1";;
    *.a) rabin2 -I "$file";;
    *.o) file --brief "$file" | sed "s/), /), \n/g;s/, B/,\nB/g" && echo "" && rabin2 -I "$file";;
    *) censor;;
esac
