#!/bin/sh

file="$1"
type=$(file --dereference --brief --mime-type "$1")

get_mime(){
    case "$type" in
        video/*|audio/*|application/octet-steam) mediainfo "$file";;
        image/*) chafa --fill=block --symbols=block -c 256 "$file";;
        text/x-shellscript) highlight --out-format=ansi "$file";;
        text/*|*/xml|application/json) highlight --out-format=ansi --force "$file";;
        application/vnd.oasis.opendocument.text|*opendocument*) odt2txt "$1";;
        application/x-executable|application/x-pie-executable|application/x-dosexec|application/x-sharedlib) file --brief "$file" | sed "s/), /), \n/g;s/, B/,\nB/g" && echo "" && rabin2 -I "$file";;
        *) cat "$1";;
    esac
}

case "$1" in
    *.zip) zipinfo "$1";;
    *.tar.gz) tar -ztvf "$1";;
    *.tar.bz2) tar -jtvf "$1";;
    *.tar) tar -tvf "$1";;
    *.a) rabin2 -I "$file";;
    *.o) file --brief "$file" | sed "s/), /), \n/g;s/, B/,\nB/g" && echo "" && rabin2 -I "$file";;
    *) get_mime;;
esac
