general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 3520
    on-timeout = ~/.local/bin/backlightctl 5000
    on-resume = ~/.local/bin/backlightctl 120000
}

listener {
    timeout = 3600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 3660
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'                            # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 3720
    on-timeout = doas mecc backlight off
    on-resume = doas mecc backlight full
}
