#!/bin/sh

# Directories
alias fr="cd ~/files"
alias dev="cd ~/files/Dev"
alias vids="cd ~/files/Videos"
alias pics="cd ~/files/Photos"
alias music="cd ~/files/Music"

# Config Files
alias cfnv="nvim ~/.config/nvim/init.vim"
alias cfsx="nvim ~/.config/sxhkd/sxhkdrc"
alias cfzsh="nvim ~/.config/zsh/.zshrc"
