#!/bin/sh

# Directories
alias fr="cd ~/files"
alias dev="cd ~/files/Dev"
alias vids="cd ~/files/Videos"
alias pics="cd ~/files/Photos"
alias music="cd ~/files/Music"

# Files
alias cfgnv="nvim ~/.config/nvim/init.vim"
alias zshrc="nvim ~/.config/zsh/.zshrc"
